[tool.poetry]
name = "codegreen"
version = "0.0.1"
description = "A wrapper for codegreen web for easier access"
authors = ["Anne Hartebrodt <anne.hartebrodt@fau.de>","Shubh Vardhan Jain <shubhvjain@gmail.com>"]
readme = "README.md"
packages = [{ include = "codegreen" }]
package-mode = true

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
requests = "^2.32.3"
numpy = "^2.2.4"
pandas = "^2.2.3"
codecarbon = "^2.8.3"
myst-parser = "^4.0.1"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
