name: Publish Docs to GitHub Pages

on:
  push:
    branches:
      - release  # Only trigger on the release branch

permissions:
  contents: read
  pages: write  # Required for GitHub Pages API
  id-token: write  # Required for authentication

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install  .
            pip install sphinx==7.4.7  # Install Sphinx and theme if needed
      - name: Move to docs folder
        run: |
          cd docs
      - name: Build Sphinx Docs
        run: |
          make html  
      - name: List files in build directory
        run: ls -R ./build/html
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 
        with:
          path: build/html/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
