# .github/workflows/deploy-docs.yml
name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - release  # Change this if your default branch is not 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write  # Required for GitHub Pages API
  id-token: write  # Required for authentication

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/source/requirements.txt

    - name: Build documentation
      run: |
        sphinx-build docs/source docs/build/html
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3 
      with:
        path: docs/build/html/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
